language: python
sudo: false
branches:
only:
  - master
python:
  - "3.5"
  - "3.6"
  - "3.7"


before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - wget -q $LTDB_SAMPLE -O ltdb_sample.zip
  - wget -q $LTDB_FULLCOUNT -O ltdb_full.zip
  - wget -q $NCDB -O ncdb.csv
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export DLPATH=`pwd`
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes pip
  - conda env create -f environment.yml python=$TRAVIS_PYTHON_VERSION
  - source activate geosnap
  - pip install python-coveralls
  - pip install pytest-cov


script:
  - python setup.py sdist >/dev/null
  - pytest --ignore=examples --ignore=geosnap/util  --cov geosnap

notifications:
    email:
        recipients:
            - sjsrey@gmail.com
            - weikang9009@gmail.com
            - levi.john.wolf@gmail.com
            - ek@knaaptime.com 
        on_success: change
        on_failure: always 

after_success:
  - coveralls
