name: geosnap
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - giddy >=2.2.1
  - libpysal
  - cenpy
  - geopandas
  - matplotlib
  - scikit-learn
  - seaborn
  - pyarrow >=0.14.1
  - appdirs
  - dash
  - dash-bootstrap-components
  - palettable
  - pip
  - tqdm
  - quilt3 >=3.1.11
  - xlrd
  - tobler >=0.4
  - proplot >=9
  - contextily
  - scikit-plot
  - mapclassify
  - descartes  
  - spopt >=0.1.1
  - s3fs
  - botocore >=1.20.21
  - segregation >=2.0
  - versioneer

  