name: geosnap
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - giddy >=2.2.1
  - libpysal
  - geopandas  >=0.9
  - matplotlib
  - scikit-learn
  - seaborn
  - pyarrow >=0.14.1
  - platformdirs
  - pip
  - tqdm
  - quilt3 >=3.6
  - xlrd
  - tobler >=0.8.2
  - contextily
  - mapclassify
  - spopt >=0.3.0
  - s3fs
  - segregation >=2.0
  - pyproj >=3
  - pandana
  - pooch
