name: osnap
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - cython
  - jupyterlab
  - geopandas
  - hdbscan
  - matplotlib
  - notebook
  - networkx
  - scikit-learn
  - seaborn
  - pyarrow
  - pip
  - pip:
    - libpysal
    - mapclassify
    - spenc
    - giddy
    - xlrd
    - cenpy
    - quilt
    - git+git://github.com/pysal/region@master
